-- Remove tables if exists
DROP TABLE IF EXISTS CUSTOMER CASCADE;
DROP TABLE IF EXISTS ORDER CASCADE;
DROP TABLE IF EXISTS ITEM CASCADE;
DROP TABLE IF EXISTS STOCK CASCADE;
DROP TABLE IF EXISTS LOCAT CASCADE;
--- Use Location because of Syntax constraints
DROP TABLE IF EXISTS WORKER

--  DDL for Table CUSTOMER
  CREATE TABLE CUSTOMER 
   (	
	CUSTOMERID VARCHAR(35) PRIMARY KEY,
    CUSNAME VARCHAR(35),
    SURNAME VARCHAR(35),
    CADDRESS VARCHAR (150), 
    BANKACCOUNT VARCHAR (50),
    PHONENUMBER VARCHAR (20),
    CUSEMAIL VARCHAR (50)
   );

--  DDL for Table ORDER
  CREATE TABLE ORDER 
   (	
	ORDERID VARCHAR(35) PRIMARY KEY, 
	FOREIGN KEY (ITEMID) REFERENCES ITEM ITEMID,
	FOREIGNKEY (CUSTOMERID) REFERENCES CUSTOMER CUSTOMERID,
	TYPE VARCHAR(35)
   );

--  DDL for Table ITEM
  CREATE TABLE ITEM 
   (	
	ITEMID VARCHAR(35) PRIMARY KEY,
	TYPE VARCHAR(35),
	PRICE DOUBLE(6,2),
	CONSOLE VARCHAR(35),
	MEDIUM VARCHAR(35), 
	ALBUM VARCHAR(35), 
	AGERATING VARCHAR(35),
	GAMELENGTH INT, 
	DESCR VARCHAR(500),
	IMAGEURL VARCHAR(500), 

   );

-- DDL for Table STOCK
CREATE TABLE STOCK
	(
		FOREIGN KEY (LOCATIONID) REFERENCES LOCAT LOCATIONID,
		FOREIGN KEY (ITEMID) REFERENCES ITEM ITEMID, 
		QUANTITY INT
	);

--  DDL for Table LOCATION
  CREATE TABLE LOCAT 
   (	
	LOCATIONID VARCHAR(35) PRIMARY KEY,
	LOCADDRESS VARCHAR(35)
   );



--  DDL for Table WORKER
  CREATE TABLE WORKER 
   (	
	WORKERID VARCHAR(35) PRIMARY KEY, 
	NAM VARCHAR(35), 
	SURNAME VARCHAR(35), 
	WORKROLE VARCHAR(35),
	PHONENUM VARCHAR(35),
	WEMAIL VARCHAR(35)
	FOREIGN KEY (LOCATIONID) REFERENCES LOCAT LOCATIONID
	--- Storing the number as a varchar in plain text for ease of use
   );

--  Implement Java method for creating the data itself to interact with? 
